### Second partner for battle: altenhof
POST http://localhost:10001/battles
Authorization: Bearer altenhof-mtcgToken


### Trade that will definitely work
POST http://localhost:10001/tradings
Authorization: Bearer kienboec-mtcgToken

{
  "CardToTrade": "8c20639d-6400-4534-bd0f-ae563f11f57a",
  "Type": "spell",
  "MinimumDamage": 50
}