### Second partner for battle: altenhof
POST http://localhost:10001/battles
Authorization: Bearer altenhof-mtcgToken


### Trade that will definitely work
POST http://localhost:10001/tradings
Authorization: Bearer kienboec-mtcgToken

{
  "CardToTrade": "d60e23cf-2238-4d49-844f-c7589ee5342e",
  "Type": "monster",
  "MinimumDamage": 5
}